CREATE TRIGGER tr_Update_KetQua
ON KETQUA
AFTER INSERT, UPDATE
AS
BEGIN
	IF UPDATE(DIEM)
	BEGIN
		UPDATE KETQUA
		SET GHICHU = 'VANG THI'
		WHERE DIEM = 0
	END

	IF EXISTS (SELECT * FROM inserted WHERE DIEM < 0 OR DIEM > 10)
	BEGIN
		RAISERROR ('Diem thi khong hop le!', 16, 1)
		ROLLBACK TRANSACTION
		RETURN
	END

	IF EXISTS (SELECT * FROM inserted WHERE DIEM = 0)
	BEGIN
		UPDATE KETQUA
		SET GHICHU = 'VANG THI'
		WHERE DIEM = 0
	END
END
